# Generated by Django 5.2.4 on 2025-08-04 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titolo Quiz')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('source_documents', models.JSONField(blank=True, default=list, verbose_name='Documenti Sorgente')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Medio'), ('hard', 'Difficile')], default='medium', max_length=10, verbose_name='Difficoltà')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite Tempo (min)')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name='Punteggio Minimo (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('is_public', models.BooleanField(default=False, verbose_name='Pubblico')),
                ('generated_by_ai', models.BooleanField(default=True, verbose_name='Generato da AI')),
                ('generation_prompt', models.TextField(blank=True, null=True, verbose_name='Prompt Generazione')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'db_table': 'medical_content_quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativi Totali')),
                ('total_completions', models.PositiveIntegerField(default=0, verbose_name='Completamenti Totali')),
                ('average_score', models.FloatField(default=0.0, verbose_name='Punteggio Medio')),
                ('average_time_seconds', models.PositiveIntegerField(default=0, verbose_name='Tempo Medio (sec)')),
                ('completion_rate', models.FloatField(default=0.0, verbose_name='Tasso Completamento')),
                ('difficulty_rating', models.FloatField(default=0.0, verbose_name='Valutazione Difficoltà')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='medical_content.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Analytics Quiz',
                'verbose_name_plural': 'Analytics Quiz',
                'db_table': 'medical_content_quizanalytics',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Corso'), ('completed', 'Completato'), ('abandoned', 'Abbandonato'), ('timed_out', 'Tempo Scaduto')], default='in_progress', max_length=20, verbose_name='Status')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Punteggio')),
                ('max_score', models.PositiveIntegerField(verbose_name='Punteggio Massimo')),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo Impiegato (sec)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniziato il')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completato il')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='medical_content.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Tentativo Quiz',
                'verbose_name_plural': 'Tentativi Quiz',
                'db_table': 'medical_content_quizattempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome Categoria Quiz')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornata il')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Categoria Quiz',
                'verbose_name_plural': 'Categorie Quiz',
                'db_table': 'medical_content_quizcategory',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_content.quizcategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(verbose_name='Testo Domanda')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Scelta Multipla'), ('true_false', 'Vero/Falso'), ('fill_blank', 'Riempi Spazi'), ('short_answer', 'Risposta Breve')], default='multiple_choice', max_length=20, verbose_name='Tipo Domanda')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Spiegazione')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Punti')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('source_text', models.TextField(blank=True, null=True, verbose_name='Testo Sorgente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='medical_content.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Domanda Quiz',
                'verbose_name_plural': 'Domande Quiz',
                'db_table': 'medical_content_quizquestion',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(verbose_name='Testo Risposta')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Risposta Corretta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Spiegazione')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='medical_content.quizquestion', verbose_name='Domanda')),
            ],
            options={
                'verbose_name': 'Risposta Quiz',
                'verbose_name_plural': 'Risposte Quiz',
                'db_table': 'medical_content_quizanswer',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome Categoria')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornata il')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_content.medicalcategory', verbose_name='Categoria Padre')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Categoria Medica',
                'verbose_name_plural': 'Categorie Mediche',
                'db_table': 'medical_content_medicalcategory',
                'ordering': ['order', 'name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Risposta Testuale')),
                ('is_correct', models.BooleanField(verbose_name='Corretta')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='Punti Assegnati')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Risposto il')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='medical_content.quizattempt', verbose_name='Tentativo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_content.quizquestion', verbose_name='Domanda')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_content.quizanswer', verbose_name='Risposta Selezionata')),
            ],
            options={
                'verbose_name': 'Risposta Quiz',
                'verbose_name_plural': 'Risposte Quiz',
                'db_table': 'medical_content_quizresponse',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
