# Prometheus configuration for FisioRAG monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "fisiorag-production"
    replica: "prometheus-01"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Rules files
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
    metrics_path: "/metrics"

  # FisioRAG Application
  - job_name: "fisiorag-api"
    static_configs:
      - targets: ["app:8000"]
    scrape_interval: 15s
    metrics_path: "/metrics"
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ["prometheus"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: app:8000

  # PostgreSQL Database
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.+)"
        replacement: "postgresql"

  # Neo4j Database
  - job_name: "neo4j"
    static_configs:
      - targets: ["neo4j:7474"]
    scrape_interval: 30s
    metrics_path: "/db/neo4j/tx/commit"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.+)"
        replacement: "neo4j"

  # Redis Cache
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.+)"
        replacement: "redis"

  # Node Exporter (System metrics)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.+)"
        replacement: "fisiorag-host"

  # cAdvisor (Container metrics)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "(.+)"
        replacement: "containers"

  # Docker Daemon
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scrape_interval: 30s
# Remote write configuration (for long-term storage)
# Uncomment if using remote storage like Thanos, Cortex, etc.
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# Remote read configuration
# remote_read:
#   - url: "http://cortex:9009/api/prom/read"
#     read_recent: true
