name: Staging Smoke Tests

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: ${{ secrets.STAGING_API_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Frontend smoke test (staging)
        if: env.API_BASE_URL != ''
        run: node frontend/scripts/smoke_test.mjs
        env:
          VITE_API_BASE_URL: ${{ env.API_BASE_URL }}
